cappseq_snv_pipeline:
    # General parameters
    samplelist: "config/samples.tsv"
    base_dir: "/home/crushton/Software/cappseq_snv_pipeline"
    ref_genome: "/reference/igenomes/Homo_sapiens/GSC/GRCh38/Sequence/WholeGenomeFasta/GRCh38_no_alt.fa"
    ref_genome_ver: "GRCh38"  # GRCh37 if GRCh37/hg19, GRCh38 if GRCh38/hg38


    # SAGE specific parameters
    hotspots_vcf: "resources/KnownHotspots.vcf.gz"
    capture_space: "/mnt/thanos_lv/pipelines/DLBCL_Montreal/PlasmaTwistCAPPSeq/coverage/00-helperfiles/twist_panel_design.noalt.sort.bed3"
    ensembl: "resources/ensembl_cache/38/"
    unmatched_normal: "/home/crushton/GenomeInABottle/MarkDuplicates/GenomeInABottle.markDup.GRCh38.bam"
    normal_name: "Normal"
    max_depth: "100000"
    min_map_qual: "40"

    # vcf2maf specific parameters
    custom_enst: "resources/custom_enst.hg38.txt"
    vep_data: "/reference/ensembl_vep_cache/"
    centre: "morin_lab"

    # Post-filtering
    exac_max_freq: 0.01
    blacklist: "resources/capture-hg38.clean_blacklist.txt"
