cappseq_snv_pipeline:
    # General parameters
    samplelist: "config/samples.tsv"
    base_dir: "__UPDATE__"
    ref_genome: "__UPDATE__" 
    ref_genome_ver: "GRCh38"  # GRCh37 if GRCh37/hg19, GRCh38 if GRCh38/hg38


    # SAGE specific parameters
    hotspots_vcf: "resources/KnownHotspots.vcf.gz"
    capture_space: "__UPDATE__"
    ensembl: "resources/ensembl_cache/38/"
    unmatched_normal: "__UPDATE__"
    normal_name: "normal"
    max_depth: "100000"
    min_map_qual: "40"

    # vcf2maf specific parameters
    custom_enst: "resources/custom_enst.hg38.txt"
    vep_data: "__UPDATE__"
    centre: "morin_lab"

    # Post-filtering
    exac_max_freq: 0.01
    blacklist: "resources/capture-hg38.clean_blacklist.txt"
    
    # Mask positions with a high incidence of N bases
    mask_script: "src/mask_n_sites.py"
    mask_threshold: "0.05"  # Fraction of N bases at a position to mask it
    mask_count: "8"  # Minimum number of N bases required to mask a position
